/* AUTO DSP CONSTANTS */
#define AUTO_DSP_USER 16
#define AUTO_DSP_DATE 10
#define AUTO_DSP_TIME 8
char GLOBAL_UNDERLINE[100];
#define AUTO_HL GLOBAL_UNDERLINE
/* LOGIN SCREEN CONSTANTS */

#define LGN_IDX_USER 0
#define LGN_IDX_PASSWORD 1

#define LGN_LEN_USER 16
#define LGN_LEN_PASSWORD 16

#define LGN_NUM_FIELDS 6 //len of fieldmap array


/* MAC CONSTANTS */
#define MAC_IDX_SELECTION 3

#define MAC_LEN_USER 16
#define MAC_LEN_DATE 10
#define MAC_LEN_TIME 8
#define MAC_LEN_SELECTION 2

#define MAC_NUM_FIELDS 19 // len of fieldmap array
